export enum MOVEMENT_TYPE_ENUM {
  INTERNAL_MOVEMENT = 1,
  SELLING = 2,
  PRODUCT_DEVOLUTUION = 3,
  PRODUCT_REPOSITION = 4,
  REVERSED = 5,
  ADJUSTMENT = 6,
  SUPPLIER_RECIPT = 7,
  INVENTORY_SCRAP = 8,
}