export enum INVENTORY_CONTEXT_ENUM {
  WAREHOUSE = 1,
  PRODUCT_RESERVATION = 2,
  AVAILABLE_FOR_SALE = 3,
  SHRINKAGE = 4,
  CLIENT_VIRTUAL = 5,
  WASTED_VIRTUAL = 6,
  INVENTORY_SUPPLIER_VIRTUAL = 7,
  ADJUSTMENT_VIRTUAL = 8,
}